version: '3'
services:
  tomcat:
    build: ./tomcat
    depends_on:
      - mysql
    ports:
      - 8080:8080
    links:
      - mysql:mysql
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps

  mysql:
    build: ./mysql
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
